import { motion } from "motion/react";
import { Gift, Percent, Info } from "lucide-react";
import { useState } from "react";

const REWARDS = [
  {
    title: "Instant Bonus",
    value: "€10",
    subtitle: "per referral",
    description: "Earn €10 instantly when your referred friend makes their first deposit of €20 or more.",
    icon: Gift,
    gradient: "from-neon-purple to-neon-blue",
    glowColor: "shadow-neon-purple/20",
    iconBg: "bg-neon-purple/15",
  },
  {
    title: "Revenue Share",
    value: "10%",
    subtitle: "for 30 days",
    description: "Earn 10% of the platform fees generated by your referred users for 30 days after they register.",
    icon: Percent,
    gradient: "from-neon-green to-neon-blue",
    glowColor: "shadow-neon-green/20",
    iconBg: "bg-neon-green/15",
  },
] as const;

export default function RewardsCards() {
  const [expandedIdx, setExpandedIdx] = useState<number | null>(null);

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.25 }}
      className="space-y-3"
    >
      <div className="flex items-center gap-2 mb-1">
        <Gift className="size-4 text-neon-purple" />
        <h3 className="font-display font-bold text-sm tracking-[0.2em] text-neon-purple uppercase">
          Rewards
        </h3>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        {REWARDS.map((reward, i) => {
          const Icon = reward.icon;
          const isExpanded = expandedIdx === i;
          return (
            <motion.div
              key={reward.title}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.4, delay: 0.3 + i * 0.1 }}
              className={`rounded-2xl bg-card/60 border border-border/40 backdrop-blur-xl p-4 relative overflow-hidden shadow-lg ${reward.glowColor}`}
            >
              {/* Gradient accent top bar */}
              <div className={`absolute top-0 left-0 right-0 h-0.5 bg-gradient-to-r ${reward.gradient}`} />

              <div className="flex items-start justify-between">
                <div className="flex items-center gap-3">
                  <div className={`w-10 h-10 rounded-xl ${reward.iconBg} flex items-center justify-center`}>
                    <Icon className="size-5 text-foreground" />
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground font-display tracking-wider uppercase">
                      {reward.title}
                    </p>
                    <div className="flex items-baseline gap-1">
                      <span className="font-display font-bold text-2xl text-foreground tracking-wider">
                        {reward.value}
                      </span>
                      <span className="text-xs text-muted-foreground">{reward.subtitle}</span>
                    </div>
                  </div>
                </div>
                <button
                  onClick={() => setExpandedIdx(isExpanded ? null : i)}
                  className="p-1.5 rounded-lg hover:bg-secondary/60 transition-colors cursor-pointer"
                >
                  <Info className="size-4 text-muted-foreground" />
                </button>
              </div>

              {/* Expandable tooltip */}
              {isExpanded && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: "auto" }}
                  exit={{ opacity: 0, height: 0 }}
                  className="mt-3 pt-3 border-t border-border/30"
                >
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    {reward.description}
                  </p>
                </motion.div>
              )}
            </motion.div>
          );
        })}
      </div>
    </motion.div>
  );
}
